### ISSUE TITLE
Watch uses wrong variable name

### ISSUE THREAD

**Issue by jeetee** [Marr11317/muscord-bot#28]
https://github.com/Marr11317/muscord-bot/blob/e94a618e6dbcee03195333aac956d8d15cdae650/app.js#L141

MuseBot just announced:
```
We reached 6100 stars in the MuseScore repo!
We reached 6100 watchers in the MuseScore repo!
```

But there are currently 248 watchers on the repo. `const stars` was already assigned by the stars notification and can't be redefined for the watch count. Seems like a small copy-paste error that wasn't refactored.

**Comment by Jojo-Schmitz** [comment]
And while at fixing that, maybe bump up the stars notification to every 1000 ?

**Comment by ecstrema** [comment]
should be closed with https://github.com/Marr11317/muscord-bot/commit/a669066ad714258d06f68fdf527b17c74300d661
